-- DROP TABLE IF EXISTS items;
CREATE TABLE IF NOT EXISTS tweets (
    id bigint UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    message varchar(255) NOT NULL,
    user_id int NOT NULL,
    image_path TEXT DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);